test:
  clients:
    default:
      database: container-broker_test
      hosts:
        - <%= ENV["MONGODB_URL"] || "localhost:27017" %>
      options:
        read:
          mode: :primary
        max_pool_size: 1
